#!/usr/bin/env bash
# 웹 빌드 단축 실행기. bin/build-web.sh 로 그대로 넘깁니다.
#
#   ./build-web                      # 테스트 후 web-build/index.html 로 내보내기
#   ./build-web -d                   # 디버그 빌드
#   ./build-web -s                   # 테스트 건너뛰기
#   ./build-web dist/index.html      # 다른 경로로
#   ./build-web -h                   # 사용법
exec "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/bin/build-web.sh" "$@"
