extends GdUnitTestSuite

# 게임 오버
func test_몬스터_모드에서_맵에_인간_캐릭터가_아웃되면_게임을_종료한다() -> void:
	var map := Map.new()
	var battle := Battle.new(map, BattleMode.MONSTER)
	var human := Character.new(Vector2i(4, 2))
	var npc := Npc.new(Vector2i(9, 10))
	map.add_character(human)
	map.add_character(npc)
	assert_bool(battle.is_game_over()).is_false()
	battle.get_map().let_character_out(human)
	battle.tick(0.1)
	assert_bool(battle.is_game_over()).is_true()

func test_몬스터_모드에서_맵에_NPC가_아웃되면_게임을_종료한다() -> void:
	var map := Map.new()
	var battle := Battle.new(map, BattleMode.MONSTER)
	var human := Character.new(Vector2i(4, 2))
	var npc := Npc.new(Vector2i(9, 10))
	map.add_character(human)
	map.add_character(npc)
	assert_bool(battle.is_game_over()).is_false()
	battle.get_map().let_character_out(npc)
	battle.tick(0.1)
	assert_bool(battle.is_game_over()).is_true()

func test_로컬멀티_모드에서_한_명이_아웃되면_게임이_종료된다() -> void:
	var map := Map.new()
	var battle := Battle.new(map, BattleMode.LOCAL_MULTI)
	var human1 := Character.new(Vector2i(4, 2), 1, Color.RED)
	var human2 := Character.new(Vector2i(9, 10), 2, Color.BLUE)
	map.add_character(human1)
	map.add_character(human2)
	assert_bool(battle.is_game_over()).is_false()
	battle.get_map().let_character_out(human1)
	battle.tick(0.1)
	assert_bool(battle.is_game_over()).is_true()

func test_게임이_종료되면_몇_초_후에_방으로_가야_함을_알린다() -> void:
	var map := Map.new()
	var battle := Battle.new(map, BattleMode.LOCAL_MULTI)
	var human1 := Character.new(Vector2i(4, 2), 1, Color.RED)
	var human2 := Character.new(Vector2i(9, 10), 2, Color.BLUE)
	map.add_character(human1)
	map.add_character(human2)
	assert_bool(battle.should_go_to_room).is_false()
	battle.get_map().let_character_out(human1)
	battle.tick(0.1)
	assert_bool(battle.is_game_over()).is_true()
	assert_bool(battle.should_go_to_room).is_false()
	battle.tick(Battle.GAME_OVER_AFTER_SECOND * 0.4)
	assert_bool(battle.should_go_to_room).is_false()
	battle.tick(Battle.GAME_OVER_AFTER_SECOND * 0.4)
	assert_bool(battle.should_go_to_room).is_false()
	battle.tick(Battle.GAME_OVER_AFTER_SECOND * 0.4)
	assert_bool(battle.should_go_to_room).is_true()
	battle.tick(Battle.GAME_OVER_AFTER_SECOND * 0.4)
	assert_bool(battle.should_go_to_room).is_false()

func test_방으로_가야_함을_알린_뒤에는_맵의_시간이_흐르지_않는다() -> void:
	var map := Map.new()
	var battle := Battle.new(map, BattleMode.LOCAL_MULTI)
	var human1 := Character.new(Vector2i(4, 2), 1, Color.RED)
	var human2 := Character.new(Vector2i(9, 10), 2, Color.BLUE)
	map.add_character(human1)
	map.add_character(human2)
	battle.get_map().let_character_out(human1)
	battle.tick(0.1)
	battle.tick(Battle.GAME_OVER_AFTER_SECOND * 0.4)
	battle.tick(Battle.GAME_OVER_AFTER_SECOND * 0.4)
	battle.tick(Battle.GAME_OVER_AFTER_SECOND * 0.4)
	assert_bool(battle.should_go_to_room).is_true()
	human2.place_water_balloon(map)
	assert_int(map.water_balloon_count()).is_equal(1)
	battle.tick(WaterBalloon.POP_AFTER_SECONDS * 2.0)
	assert_int(map.water_balloon_count()).is_equal(1)

# 승패
func test_하나의_배틀에서_승패가_난_후에_또_다시_승패가_나지_않는다() -> void:
	var map := Map.new()
	var battle := Battle.new(map, BattleMode.MONSTER)
	var human := Character.new(Vector2i(4, 2))
	var npc := Npc.new(Vector2i(9, 10), 0, Color.BLUE)
	map.add_character(human)
	map.add_character(npc)
	assert_bool(battle.is_game_over()).is_false()
	assert_that(battle.winner).is_not_equal(Color.BLUE)
	battle.get_map().let_character_out(human)
	battle.tick(0.1)
	assert_bool(battle.is_game_over()).is_true()
	assert_that(battle.winner).is_equal(Color.BLUE)
	battle.get_map().let_character_out(npc)
	battle.tick(0.1)
	assert_bool(battle.is_game_over()).is_true()
	assert_that(battle.winner).is_equal(Color.BLUE)

func test_몬스터_모드에서_맵에_인간_캐릭터가_모두_아웃되면_게임에서_진다() -> void:
	var map := Map.new()
	var battle := Battle.new(map, BattleMode.MONSTER)
	var human := Character.new(Vector2i(4, 2))
	var npc := Npc.new(Vector2i(9, 10), 0, Color.BLUE)
	map.add_character(human)
	map.add_character(npc)
	assert_that(battle.winner).is_not_equal(Color.BLUE)
	battle.get_map().let_character_out(human)
	battle.tick(0.1)
	assert_that(battle.winner).is_equal(Color.BLUE)

func test_몬스터_모드에서_맵에_NPC가_모두_아웃되면_게임에서_이긴다() -> void:
	var map := Map.new()
	var battle := Battle.new(map, BattleMode.MONSTER)
	var human := Character.new(Vector2i(4, 2))
	var npc := Npc.new(Vector2i(9, 10), 0, Color.BLUE)
	map.add_character(human)
	map.add_character(npc)
	assert_that(battle.winner).is_not_equal(Color.RED)
	battle.get_map().let_character_out(npc)
	battle.tick(0.1)
	assert_that(battle.winner).is_equal(Color.RED)

func test_몬스터_모드에서_맵에_인간_캐릭터와_NPC_모두_아웃되면_무승부가_된다() -> void:
	var map := Map.new()
	var battle := Battle.new(map, BattleMode.MONSTER)
	var human := Character.new(Vector2i(4, 2))
	var npc := Npc.new(Vector2i(9, 10), 0, Color.BLUE)
	map.add_character(human)
	map.add_character(npc)
	assert_bool(battle.is_draw).is_false()
	human.place_water_balloon(map)
	npc.place_water_balloon(map)
	battle.tick(WaterBalloon.POP_AFTER_SECONDS)
	battle.tick(Bubble.ALIVE_SECONDS * 2.0)
	assert_bool(battle.is_draw).is_true()

func test_로컬멀티_모드에서_이긴_팀이_승리한다() -> void:
	var map := Map.new()
	var battle := Battle.new(map, BattleMode.LOCAL_MULTI)
	var human1 := Character.new(Vector2i(4, 2), 1, Color.RED)
	var human2 := Character.new(Vector2i(9, 10), 2, Color.BLUE)
	map.add_character(human1)
	map.add_character(human2)
	battle.get_map().let_character_out(human1)
	battle.tick(0.1)
	assert_bool(battle.has_winner()).is_true()
	assert_that(battle.winner).is_equal(Color.BLUE)

func test_로컬멀티_모드에서_모든_팀이_아웃되면_무승부로_끝난다() -> void:
	var map := Map.new()
	var battle := Battle.new(map, BattleMode.LOCAL_MULTI)
	var human1 := Character.new(Vector2i(4, 2), 1, Color.RED)
	var human2 := Character.new(Vector2i(9, 10), 2, Color.BLUE)
	map.add_character(human1)
	map.add_character(human2)
	battle.get_map().let_character_out(human1)
	battle.get_map().let_character_out(human2)
	battle.tick(0.1)
	assert_bool(battle.has_winner()).is_false()
	assert_bool(battle.is_draw).is_true()
